/**
 * AgriTrade Hub AI - Master Product Catalog
 * Single Source of Truth for Server & Database Seeding
 * Strict product-specific media mapping.
 */

export const masterProductCatalog = [
  // 1. VEGETABLES
  {
    _id: 'prod_01',
    id: 'prod_01',
    productId: 'p001',
    name: 'Fresh Farm Tomatoes',
    category: 'Vegetables',
    description: 'Vine-ripened, naturally cultivated Grade A hybrid tomatoes with firm texture and high lycopene content. Directly harvested from Guntur farm clusters.',
    specifications: {
      variety: 'Abhinav Hybrid Red',
      grade: 'Grade A',
      moistureContent: '92%',
      shelfLife: '10-12 Days under cold chain',
      packaging: '25 kg plastic perforated crates',
      organicCertified: true,
      fpoSource: 'Guntur Kisan Producers Cooperative',
    },
    price: 32,
    unit: 'kg',
    stock: 2500,
    minOrderQuantity: 5,
    farmerName: 'Ramesh Reddy (Kisan Samiti)',
    sellerName: 'Guntur Vegetable Hub',
    location: { city: 'Guntur', state: 'Andhra Pradesh', lat: 16.3067, lng: 80.4365 },
    harvestDate: '2026-10-05',
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 38,
    image: '/products/p001/image-1.jpg',
    images: [
      '/products/p001/image-1.jpg',
      '/products/p001/image-2.jpg',
      '/products/p001/image-3.jpg',
    ],
    gallery: [
      '/products/p001/image-1.jpg',
      '/products/p001/image-2.jpg',
      '/products/p001/image-3.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_02',
    id: 'prod_02',
    productId: 'p002',
    name: 'Nasik Red Onions',
    category: 'Vegetables',
    description: 'Medium to large pungent red onions directly harvested from fertile Nasik volcanic soils. Exceptional curing and long storage shelf-life.',
    specifications: {
      variety: 'Nasik Garwa Red',
      grade: 'Grade A Export',
      moistureContent: '14%',
      shelfLife: '45-60 Days',
      packaging: '50 kg breathable red mesh sacks',
      organicCertified: false,
      fpoSource: 'Lasalgaon Mandi Cooperative',
    },
    price: 28,
    unit: 'kg',
    stock: 4500,
    minOrderQuantity: 10,
    farmerName: 'Balasaheb Patil',
    sellerName: 'Maharashtra Krishi Vyapar',
    location: { city: 'Nashik', state: 'Maharashtra', lat: 19.9975, lng: 73.7898 },
    harvestDate: '2026-10-02',
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 54,
    image: '/products/p002/image-1.jpg',
    images: [
      '/products/p002/image-1.jpg',
      '/products/p002/image-2.jpg',
      '/products/p002/image-3.jpg',
      '/products/p002/image-4.jpg',
    ],
    gallery: [
      '/products/p002/image-1.jpg',
      '/products/p002/image-2.jpg',
      '/products/p002/image-3.jpg',
      '/products/p002/image-4.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_03',
    id: 'prod_03',
    productId: 'p003',
    name: 'Agra Jyoti Potatoes',
    category: 'Vegetables',
    description: 'Thin-skinned, starch-rich high quality table potatoes. Clean washed, zero greening, uniform oval tubers ideal for household and bulk culinary processing.',
    specifications: {
      variety: 'Kufri Jyoti Table Potato',
      grade: 'Grade A',
      moistureContent: '78%',
      shelfLife: '30-40 Days in cold storage',
      packaging: '50 kg ventilated jute bags',
      organicCertified: false,
      fpoSource: 'Yamuna Riverbank Farmers FPO',
    },
    price: 22,
    unit: 'kg',
    stock: 6000,
    minOrderQuantity: 10,
    farmerName: 'Suresh Kumar Yadav',
    sellerName: 'Yamuna Agri Traders',
    location: { city: 'Agra', state: 'Uttar Pradesh', lat: 27.1767, lng: 78.0081 },
    harvestDate: '2026-10-04',
    quality: 'Grade A',
    rating: 4.6,
    reviewsCount: 42,
    image: '/products/p003/image-1.jpg',
    images: [
      '/products/p003/image-1.jpg',
      '/products/p003/image-2.jpg',
      '/products/p003/image-3.jpg',
      '/products/p003/image-4.jpg',
    ],
    gallery: [
      '/products/p003/image-1.jpg',
      '/products/p003/image-2.jpg',
      '/products/p003/image-3.jpg',
      '/products/p003/image-4.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_09',
    id: 'prod_09',
    productId: 'p009',
    name: 'Fresh Pungent Green Chillies',
    category: 'Vegetables',
    description: 'Crisp, spicy green chillies handpicked fresh at dawn. Glossy skin, ideal pungent heat (Scoville 35,000-45,000 SHU).',
    specifications: {
      variety: 'G-4 Green Hot Chilli',
      grade: 'Grade A',
      moistureContent: '85%',
      shelfLife: '7-10 Days',
      packaging: '10 kg ventilated carton boxes',
      organicCertified: false,
      fpoSource: 'Kolar Horticultural Collective',
    },
    price: 48,
    unit: 'kg',
    stock: 900,
    minOrderQuantity: 5,
    farmerName: 'Santosh Gowda',
    sellerName: 'Kolar Horticultural Collective',
    location: { city: 'Kolar', state: 'Karnataka', lat: 13.1367, lng: 78.1291 },
    harvestDate: '2026-10-06',
    quality: 'Grade A',
    rating: 4.6,
    reviewsCount: 22,
    image: '/products/p009/image-1.jpg',
    images: [
      '/products/p009/image-1.jpg',
    ],
    gallery: [
      '/products/p009/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_17',
    id: 'prod_17',
    productId: 'p017',
    name: 'Fresh Leafy Coriander Bunches',
    category: 'Vegetables',
    description: 'Aromatic farm-fresh green coriander with crisp stems and vibrant serrated leaves. Clean soil roots washed.',
    specifications: {
      variety: 'Desi Khushboo Coriander',
      grade: 'Grade A',
      moistureContent: '90%',
      shelfLife: '4-5 Days chilled',
      packaging: '5 kg wet-wrapped bundles',
      organicCertified: true,
      fpoSource: 'Pune Peri-Urban Organic Farms',
    },
    price: 35,
    unit: 'kg',
    stock: 650,
    minOrderQuantity: 5,
    farmerName: 'Sunita Deshmukh',
    sellerName: 'Western Ghats BioAgri',
    location: { city: 'Pune', state: 'Maharashtra', lat: 18.5204, lng: 73.8567 },
    harvestDate: '2026-10-07',
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 19,
    image: '/products/p017/image-1.jpg',
    images: [
      '/products/p017/image-1.jpg',
    ],
    gallery: [
      '/products/p017/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  
  {
    _id: 'prod_20',
    id: 'prod_20',
    productId: 'p020',
    name: 'Crunchy Orange Carrots',
    category: 'Vegetables',
    description: 'Sweet, crisp, beta-carotene rich deep orange carrots. Machine washed and graded, uniform taper, tender juicy core.',
    specifications: {
      variety: 'Pusa Kesar Orange',
      grade: 'Grade A Export',
      moistureContent: '88%',
      shelfLife: '14-20 Days cold stored',
      packaging: '20 kg perforated poly mesh bags',
      organicCertified: false,
      fpoSource: 'Hoshiarpur Cold Chain Logistics',
    },
    price: 36,
    unit: 'kg',
    stock: 2200,
    minOrderQuantity: 5,
    farmerName: 'Jagjit Sandhu',
    sellerName: 'Hoshiarpur Cold Chain Logistics',
    location: { city: 'Hoshiarpur', state: 'Punjab', lat: 31.5273, lng: 75.9149 },
    harvestDate: '2026-10-04',
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 26,
    image: '/products/p020/image-1.jpg',
    images: [
      '/products/p020/image-1.jpg',
    ],
    gallery: [
      '/products/p020/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_21',
    id: 'prod_21',
    productId: 'p021',
    name: 'Purple Glossy Brinjal (Eggplant)',
    category: 'Vegetables',
    description: 'Glossy dark purple teardrop eggplants with minimal seed cavity. Tender flesh, zero pest damage, harvested in cool morning hours.',
    specifications: {
      variety: 'Bhagyamati Purple Oval',
      grade: 'Grade A',
      moistureContent: '91%',
      shelfLife: '6-8 Days',
      packaging: '15 kg corrugated ventilated boxes',
      organicCertified: true,
      fpoSource: 'Warangal Krishi Mandi',
    },
    price: 30,
    unit: 'kg',
    stock: 1400,
    minOrderQuantity: 5,
    farmerName: 'Prabhakar Rao',
    sellerName: 'Warangal Krishi Mandi',
    location: { city: 'Warangal', state: 'Telangana', lat: 17.9689, lng: 79.5941 },
    harvestDate: '2026-10-06',
    quality: 'Grade A',
    rating: 4.6,
    reviewsCount: 21,
    image: '/products/p021/image-1.jpg',
    images: [
      '/products/p021/image-1.jpg',
    ],
    gallery: [
      '/products/p021/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_22',
    id: 'prod_22',
    productId: 'p022',
    name: 'Tender Green Okra (Bhindi)',
    category: 'Vegetables',
    description: 'Slender, snap-fresh green okra pods with zero fiber stringiness. Harvested early morning for peak tenderness.',
    specifications: {
      variety: 'Radhika Hybrid Ladyfinger',
      grade: 'Grade A',
      moistureContent: '88%',
      shelfLife: '5-6 Days',
      packaging: '15 kg corrugated boxes',
      organicCertified: false,
      fpoSource: 'Nashik Vegetable Growers Union',
    },
    price: 36,
    unit: 'kg',
    stock: 1100,
    minOrderQuantity: 5,
    farmerName: 'Dnyaneshwar Shinde',
    sellerName: 'Godavari Agri Producers',
    location: { city: 'Nashik', state: 'Maharashtra', lat: 19.9975, lng: 73.7898 },
    harvestDate: '2026-10-06',
    quality: 'Grade A',
    rating: 4.6,
    reviewsCount: 28,
    image: '/products/p022/image-1.jpg',
    images: [
      '/products/p022/image-1.jpg',
      '/products/p022/image-2.jpg',
    ],
    gallery: [
      '/products/p022/image-1.jpg',
      '/products/p022/image-2.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_23',
    id: 'prod_23',
    productId: 'p023',
    name: 'Snow White Cauliflower',
    category: 'Vegetables',
    description: 'Dense, compact snow-white curds protected by lush green jacket leaves. Free from blemishes or insect marks.',
    specifications: {
      variety: 'Pusa Snowball K-1',
      grade: 'Grade A',
      moistureContent: '90%',
      shelfLife: '8-10 Days',
      packaging: 'Crated with jacket leaves intact',
      organicCertified: false,
      fpoSource: 'Yamuna Khadir Kisan Sangh',
    },
    price: 34,
    unit: 'kg',
    stock: 1400,
    minOrderQuantity: 10,
    farmerName: 'Mahesh Chand',
    sellerName: 'Agra Mandi Merchant Syndicate',
    location: { city: 'Agra', state: 'Uttar Pradesh', lat: 27.1767, lng: 78.0081 },
    harvestDate: '2026-10-05',
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 31,
    image: '/products/p023/image-1.jpg',
    images: [
      '/products/p023/image-1.jpg',
    ],
    gallery: [
      '/products/p023/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_24',
    id: 'prod_24',
    productId: 'p024',
    name: 'Crisp Green Cabbage',
    category: 'Vegetables',
    description: 'Round, tightly wrapped green cabbage heads. Sweet peppery crunch, zero pesticide residue.',
    specifications: {
      variety: 'Golden Acre Compact',
      grade: 'Grade A',
      moistureContent: '91%',
      shelfLife: '14-18 Days',
      packaging: '30 kg ventilated sacks',
      organicCertified: false,
      fpoSource: 'Ooty Highland Farmers Society',
    },
    price: 24,
    unit: 'kg',
    stock: 2200,
    minOrderQuantity: 10,
    farmerName: 'K. Selvan',
    sellerName: 'Nilgiri Produce Aggregators',
    location: { city: 'Ooty', state: 'Tamil Nadu', lat: 11.4102, lng: 76.6950 },
    harvestDate: '2026-10-04',
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 26,
    image: '/products/p024/image-1.jpg',
    images: [
      '/products/p024/image-1.jpg',
      '/products/p024/image-2.jpg',
    ],
    gallery: [
      '/products/p024/image-1.jpg',
      '/products/p024/image-2.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_25',
    id: 'prod_25',
    productId: 'p025',
    name: 'Shimla Green Bell Capsicum',
    category: 'Vegetables',
    description: 'Glossy 3-to-4 lobe blocky green capsicums with thick juicy walls. Grown in polyhouse climate-controlled conditions.',
    specifications: {
      variety: 'Indra F1 Hybrid',
      grade: 'Grade A Polyhouse',
      moistureContent: '93%',
      shelfLife: '12-14 Days chilled',
      packaging: '10 kg telescopic carton boxes',
      organicCertified: false,
      fpoSource: 'Shimla Valley Flora & Veg',
    },
    price: 52,
    unit: 'kg',
    stock: 850,
    minOrderQuantity: 5,
    farmerName: 'Ravi Thakur',
    sellerName: 'Himachal Cold Chain Apex',
    location: { city: 'Shimla', state: 'Himachal Pradesh', lat: 31.1048, lng: 77.1734 },
    harvestDate: '2026-10-06',
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 33,
    image: '/products/p025/image-1.jpg',
    images: [
      '/products/p025/image-1.jpg',
      '/products/p025/image-2.jpg',
    ],
    gallery: [
      '/products/p025/image-1.jpg',
      '/products/p025/image-2.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_26',
    id: 'prod_26',
    productId: 'p026',
    name: 'Fresh Farm Spinach (Palak)',
    category: 'Vegetables',
    description: 'Tender broad green palak leaves packed with bioavailable iron and minerals. Cut fresh from organic fertile soil beds.',
    specifications: {
      variety: 'All Green Broad Leaf',
      grade: 'Organic Certified',
      moistureContent: '92%',
      shelfLife: '3-4 Days chilled',
      packaging: 'Cooled bunches in air-permeable cartons',
      organicCertified: true,
      fpoSource: 'Malwa Organic Farmers Union',
    },
    price: 30,
    unit: 'kg',
    stock: 500,
    minOrderQuantity: 5,
    farmerName: 'Gopal Patidar',
    sellerName: 'Indore Bio Agri Market',
    location: { city: 'Indore', state: 'Madhya Pradesh', lat: 22.7196, lng: 75.8577 },
    harvestDate: '2026-10-07',
    quality: 'Organic Certified',
    rating: 4.9,
    reviewsCount: 29,
    image: '/products/p026/image-1.jpg',
    images: [
      '/products/p026/image-1.jpg',
    ],
    gallery: [
      '/products/p026/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },

  // 2. FRUITS
  {
    _id: 'prod_04',
    id: 'prod_04',
    productId: 'p004',
    name: 'Banganapalli Golden Mangoes',
    category: 'Fruits',
    description: 'Geographical Indication (GI) tagged royal sweet mangoes. Fiberless golden pulp, naturally tree-ripened with zero calcium carbide.',
    specifications: {
      variety: 'Banganapalli (Benishan) GI Tag',
      grade: 'Export Grade Premium',
      sugarBrix: '18-20° Brix',
      shelfLife: '8-10 Days',
      packaging: '5 kg export foam net cushioned cartons',
      organicCertified: true,
      fpoSource: 'Rayalaseema Fruit Growers FPO',
    },
    price: 130,
    unit: 'kg',
    stock: 1200,
    minOrderQuantity: 5,
    farmerName: 'Venkat Rao Orchards',
    sellerName: 'Rayalaseema Fruit FPO',
    location: { city: 'Kurnool', state: 'Andhra Pradesh', lat: 15.8281, lng: 78.0373 },
    harvestDate: '2026-10-03',
    quality: 'Export Quality',
    rating: 4.9,
    reviewsCount: 78,
    image: '/products/p004/image-1.jpg',
    images: [
      '/products/p004/image-1.jpg',
      '/products/p004/image-2.jpg',
      '/products/p004/image-3.jpg',
    ],
    gallery: [
      '/products/p004/image-1.jpg',
      '/products/p004/image-2.jpg',
      '/products/p004/image-3.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_05',
    id: 'prod_05',
    productId: 'p005',
    name: 'Robusta Golden Bananas',
    category: 'Fruits',
    description: 'Sweet, energy-rich unblemished Robusta bananas harvested fresh from Cauvery delta groves. Controlled ripening, zero ethylene damage.',
    specifications: {
      variety: 'Grand Naine Robusta',
      grade: 'Grade A+',
      sugarBrix: '22° Brix',
      shelfLife: '6-8 Days',
      packaging: '13 kg CFB boxes with plastic lining',
      organicCertified: true,
      fpoSource: 'Tamil Nadu Banana Growers Guild',
    },
    price: 45,
    unit: 'kg',
    stock: 1800,
    minOrderQuantity: 5,
    farmerName: 'Murugan Thottam',
    sellerName: 'Tamil Nadu Banana Growers',
    location: { city: 'Tiruchirappalli', state: 'Tamil Nadu', lat: 10.7905, lng: 78.7047 },
    harvestDate: '2026-10-05',
    quality: 'Grade A+',
    rating: 4.7,
    reviewsCount: 31,
    image: '/products/p005/image-1.jpg',
    images: [
      '/products/p005/image-1.jpg',
      '/products/p005/image-2.jpg',
      '/products/p005/image-3.jpg',
      '/products/p005/image-4.jpg',
    ],
    gallery: [
      '/products/p005/image-1.jpg',
      '/products/p005/image-2.jpg',
      '/products/p005/image-3.jpg',
      '/products/p005/image-4.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_27',
    id: 'prod_27',
    productId: 'p027',
    name: 'Ratnagiri Alphonso Mangoes (Hapus)',
    category: 'Fruits',
    description: 'The indisputable King of Mangoes from coastal laterite soil of Ratnagiri. Unmatched saffron aroma, non-fibrous melt-in-mouth texture.',
    specifications: {
      variety: 'Ratnagiri Hapus GI Tag',
      grade: 'Export Super Grade',
      sugarBrix: '22-24° Brix',
      shelfLife: '7-10 Days',
      packaging: 'Traditional straw-lined wooden export crates (12 pcs)',
      organicCertified: true,
      fpoSource: 'Devgad & Ratnagiri Hapus Growers Trust',
    },
    price: 320,
    unit: 'kg',
    stock: 550,
    minOrderQuantity: 5,
    farmerName: 'Vinayak Sawant',
    sellerName: 'Konkan Fruit Orchards',
    location: { city: 'Ratnagiri', state: 'Maharashtra', lat: 16.9902, lng: 73.3120 },
    harvestDate: '2026-10-02',
    quality: 'Export Quality',
    rating: 5.0,
    reviewsCount: 94,
    image: '/products/p027/image-1.jpg',
    images: [
      '/products/p027/image-1.jpg',
    ],
    gallery: [
      '/products/p027/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_28',
    id: 'prod_28',
    productId: 'p028',
    name: 'Kashmir Red Delicious Apples',
    category: 'Fruits',
    description: 'Crisp, sweet mountain apples from high-altitude orchards of Sopore. Deep crimson skin, floral fragrance, and dense crunchy bite.',
    specifications: {
      variety: 'Kashmir Red Delicious',
      grade: 'Grade A Royal',
      sugarBrix: '15-16° Brix',
      shelfLife: '45-60 Days refrigerated',
      packaging: '10 kg tray packed telescopic cartons',
      organicCertified: false,
      fpoSource: 'J&K Apple Growers Collective',
    },
    price: 115,
    unit: 'kg',
    stock: 2400,
    minOrderQuantity: 10,
    farmerName: 'Bashir Ahmed Lone',
    sellerName: 'Sopore Apple Mandi Terminal',
    location: { city: 'Baramulla', state: 'Jammu & Kashmir', lat: 34.2000, lng: 74.3400 },
    harvestDate: '2026-10-01',
    quality: 'Grade A',
    rating: 4.9,
    reviewsCount: 62,
    image: '/products/p028/image-1.jpg',
    images: [
      '/products/p028/image-1.jpg',
      '/products/p028/image-2.jpg',
      '/products/p028/image-3.jpg',
    ],
    gallery: [
      '/products/p028/image-1.jpg',
      '/products/p028/image-2.jpg',
      '/products/p028/image-3.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_29',
    id: 'prod_29',
    productId: 'p029',
    name: 'Solapur Bhagwa Pomegranates',
    category: 'Fruits',
    description: 'Deep red, glossy arils with soft seeds and high antioxidant juice content. GI tagged export grade Bhagwa variety.',
    specifications: {
      variety: 'Bhagwa Kesar GI Tag',
      grade: 'Export Grade 300g+',
      sugarBrix: '16° Brix',
      shelfLife: '20-25 Days',
      packaging: '3.5 kg export cartons with molded trays',
      organicCertified: false,
      fpoSource: 'Solapur Anar Producers Federation',
    },
    price: 140,
    unit: 'kg',
    stock: 1600,
    minOrderQuantity: 10,
    farmerName: 'Sanjay More',
    sellerName: 'Deccan Agro Exports',
    location: { city: 'Solapur', state: 'Maharashtra', lat: 17.6599, lng: 75.9064 },
    harvestDate: '2026-10-04',
    quality: 'Export Quality',
    rating: 4.8,
    reviewsCount: 45,
    image: '/products/p029/image-1.jpg',
    images: [
      '/products/p029/image-1.jpg',
      '/products/p029/image-2.jpg',
      '/products/p029/image-3.jpg',
    ],
    gallery: [
      '/products/p029/image-1.jpg',
      '/products/p029/image-2.jpg',
      '/products/p029/image-3.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_30',
    id: 'prod_30',
    productId: 'p030',
    name: 'Nagpur Sweet Mandarin Oranges',
    category: 'Fruits',
    description: 'Loose-skinned sweet and tangy juicy mandarin oranges. Sun-bathed orchards of Vidarbha with rich vitamin C content.',
    specifications: {
      variety: 'Nagpur Santra GI Tag',
      grade: 'Grade A Special',
      sugarBrix: '12-14° Brix',
      shelfLife: '12-15 Days',
      packaging: '10 kg vented corrugated boxes',
      organicCertified: false,
      fpoSource: 'Vidarbha Citrus Cooperative Guild',
    },
    price: 65,
    unit: 'kg',
    stock: 2800,
    minOrderQuantity: 15,
    farmerName: 'Prakash Raut',
    sellerName: 'Orange City Mandi Traders',
    location: { city: 'Nagpur', state: 'Maharashtra', lat: 21.1458, lng: 79.0882 },
    harvestDate: '2026-10-03',
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 39,
    image: '/products/p030/image-1.jpg',
    images: [
      '/products/p030/image-1.jpg',
      '/products/p030/image-2.jpg',
      '/products/p030/image-3.jpg',
      '/products/p030/image-4.jpg',
    ],
    gallery: [
      '/products/p030/image-1.jpg',
      '/products/p030/image-2.jpg',
      '/products/p030/image-3.jpg',
      '/products/p030/image-4.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },

  // 3. GRAINS
  {
    _id: 'prod_06',
    id: 'prod_06',
    productId: 'p006',
    name: 'Aromatic Basmati Rice (1121)',
    category: 'Grains',
    description: 'Premium aged extra-long slender basmati grain. Exceptional aroma, cooks up to 2.5 times length with separate non-sticky grains.',
    specifications: {
      variety: 'Pusa 1121 Extra Long Grain',
      grade: 'Export Quality Aged 2 Years',
      moistureContent: '11.5%',
      grainLength: '8.35 mm average raw length',
      packaging: '25 kg multi-wall polypropylene woven bags',
      organicCertified: false,
      fpoSource: 'Majha Agro Producers Association',
    },
    price: 95,
    unit: 'kg',
    stock: 5000,
    minOrderQuantity: 25,
    farmerName: 'Gurpreet Singh',
    sellerName: 'Punjab Agro Exports',
    location: { city: 'Amritsar', state: 'Punjab', lat: 31.6340, lng: 74.8723 },
    harvestDate: '2026-09-15',
    quality: 'Export Quality',
    rating: 4.9,
    reviewsCount: 65,
    image: '/products/p006/image-1.jpg',
    images: [
      '/products/p006/image-1.jpg',
    ],
    gallery: [
      '/products/p006/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_07',
    id: 'prod_07',
    productId: 'p007',
    name: 'MP Sharbati Golden Wheat',
    category: 'Grains',
    description: 'Known as the King of Wheat from the rainfed black soils of Sehore. Heavy grain weight, golden luster, and natural sweet dough taste.',
    specifications: {
      variety: 'Sehore C-306 Sharbati',
      grade: 'Grade A Premium',
      proteinContent: '13.8%',
      moistureContent: '10.5%',
      packaging: '50 kg food-grade gunny bags',
      organicCertified: true,
      fpoSource: 'Narmada Valley Farmers Cooperative',
    },
    price: 42,
    unit: 'kg',
    stock: 7500,
    minOrderQuantity: 50,
    farmerName: 'Anand Sharma',
    sellerName: 'Narmada Grain Syndicate',
    location: { city: 'Bhopal', state: 'Madhya Pradesh', lat: 23.2599, lng: 77.4126 },
    harvestDate: '2026-09-20',
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 49,
    image: '/products/p007/image-1.jpg',
    images: [
      '/products/p007/image-1.jpg',
    ],
    gallery: [
      '/products/p007/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_12',
    id: 'prod_12',
    productId: 'p012',
    name: 'Golden Yellow Maize / Corn',
    category: 'Grains',
    description: 'Uniform golden yellow dried maize kernels. Clean machine de-husked, zero fungal aflatoxin, high calorie starch yield.',
    specifications: {
      variety: 'Pioneer 3396 Hybrid Yellow Corn',
      grade: 'Grade A Feed & Industrial Food Grade',
      moistureContent: '12%',
      purity: '99%',
      packaging: '50 kg PP bags',
      organicCertified: false,
      fpoSource: 'Davangere Maize Producers Union',
    },
    price: 24,
    unit: 'kg',
    stock: 8200,
    minOrderQuantity: 100,
    farmerName: 'Basavarajappa M.',
    sellerName: 'Karnataka Grain Hub',
    location: { city: 'Davangere', state: 'Karnataka', lat: 14.4644, lng: 75.9218 },
    harvestDate: '2026-09-28',
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 36,
    image: '/products/p012/image-1.jpg',
    images: [
      '/products/p012/image-1.jpg',
      '/products/p012/image-2.jpg',
      '/products/p012/image-3.jpg',
    ],
    gallery: [
      '/products/p012/image-1.jpg',
      '/products/p012/image-2.jpg',
      '/products/p012/image-3.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_31',
    id: 'prod_31',
    productId: 'p031',
    name: 'Andhra Sona Masoori Raw Rice',
    category: 'Grains',
    description: 'Lightweight, low-starch aromatic medium-grain raw white rice grown in the fertile Krishna-Godavari delta basin.',
    specifications: {
      variety: 'BPT 5204 (Samba Mahsuri)',
      grade: 'Grade A Aged 12 Months',
      moistureContent: '12%',
      brokenPercentage: '<2%',
      packaging: '26 kg HDPE bags',
      organicCertified: false,
      fpoSource: 'Krishna Delta Paddy Farmers Union',
    },
    price: 58,
    unit: 'kg',
    stock: 6500,
    minOrderQuantity: 25,
    farmerName: 'Venkateswara Rao',
    sellerName: 'Vijayawada Millers Guild',
    location: { city: 'Vijayawada', state: 'Andhra Pradesh', lat: 16.5062, lng: 80.6480 },
    harvestDate: '2026-09-18',
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 52,
    image: '/products/p031/image-1.jpg',
    images: [
      '/products/p031/image-1.jpg',
    ],
    gallery: [
      '/products/p031/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_32',
    id: 'prod_32',
    productId: 'p032',
    name: 'Organic Finger Millet (Ragi)',
    category: 'Grains',
    description: 'Nutrient-dense ancient whole red-brown finger millet grains. Superfood rich in dietary fiber, amino acids, and plant calcium.',
    specifications: {
      variety: 'GPU-28 Mandya Local Ragi',
      grade: 'Certified Organic',
      calciumContent: '344 mg/100g',
      moistureContent: '10%',
      packaging: '30 kg jute bags with poly-liner',
      organicCertified: true,
      fpoSource: 'Mandya Organic Farmers Collective',
    },
    price: 46,
    unit: 'kg',
    stock: 3100,
    minOrderQuantity: 20,
    farmerName: 'Siddegowda K.',
    sellerName: 'Mysuru Organic Alliance',
    location: { city: 'Mandya', state: 'Karnataka', lat: 12.5226, lng: 76.8976 },
    harvestDate: '2026-09-22',
    quality: 'Organic Certified',
    rating: 4.9,
    reviewsCount: 44,
    image: '/products/p032/image-1.jpg',
    images: [
      '/products/p032/image-1.jpg',
    ],
    gallery: [
      '/products/p032/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },

  // 4. SPICES
  {
    _id: 'prod_08',
    id: 'prod_08',
    productId: 'p008',
    name: 'Guntur Teja Red Chillies',
    category: 'Spices',
    description: 'Fiery hot, intense red stemless dried chillies world-famous from Asia\'s largest chilli market. High capsaicin pungency (75,000-85,000 SHU).',
    specifications: {
      variety: 'S17 Teja Hot Stemless',
      grade: 'Export Quality ASTA Red',
      capsaicin: '0.85%',
      moistureContent: '<10%',
      packaging: '25 kg jute bales with outer plastic wrap',
      organicCertified: false,
      fpoSource: 'Guntur Spice Merchants Association',
    },
    price: 220,
    unit: 'kg',
    stock: 3200,
    minOrderQuantity: 10,
    farmerName: 'Koteswara Rao',
    sellerName: 'Guntur Spice Merchants Association',
    location: { city: 'Guntur', state: 'Andhra Pradesh', lat: 16.3067, lng: 80.4365 },
    harvestDate: '2026-09-10',
    quality: 'Export Quality',
    rating: 4.9,
    reviewsCount: 92,
    image: '/products/p008/image-1.jpg',
    images: [
      '/products/p008/image-1.jpg',
    ],
    gallery: [
      '/products/p008/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_10',
    id: 'prod_10',
    productId: 'p010',
    name: 'Lakadong High-Curcumin Turmeric',
    category: 'Spices',
    description: 'World-renowned turmeric with over 7.5% natural curcumin content from Jaintia Hills. Intense aromatic earthy flavor and medicinal purity.',
    specifications: {
      variety: 'Lakadong Indigenous GI Tag',
      grade: 'Organic Certified Grade A',
      curcuminPercentage: '7.8% verified by laboratory test',
      moistureContent: '8%',
      packaging: '25 kg vacuum-sealed foil-lined bags',
      organicCertified: true,
      fpoSource: 'Jaintia Organic Hills FPO',
    },
    price: 180,
    unit: 'kg',
    stock: 1400,
    minOrderQuantity: 5,
    farmerName: 'Lakhon Warjri',
    sellerName: 'Jaintia Organic Hills FPO',
    location: { city: 'Shillong', state: 'Meghalaya', lat: 25.5788, lng: 91.8933 },
    harvestDate: '2026-09-08',
    quality: 'Organic Certified',
    rating: 5.0,
    reviewsCount: 46,
    image: '/products/p010/image-1.jpg',
    images: [
      '/products/p010/image-1.jpg',
    ],
    gallery: [
      '/products/p010/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_18',
    id: 'prod_18',
    productId: 'p018',
    name: 'Ooty White Garlic Bulbs',
    category: 'Spices',
    description: 'Firm, multi-clove white garlic grown in high-altitude cool climates. Pungent allicin concentration with dense medicinal aroma.',
    specifications: {
      variety: 'Nilgiri Hill White Extra Bold',
      grade: 'Grade A Bold',
      moistureContent: '65%',
      shelfLife: '60-90 Days well ventilated',
      packaging: '25 kg mesh open-air bags',
      organicCertified: false,
      fpoSource: 'Nilgiri Garlic Producers Network',
    },
    price: 165,
    unit: 'kg',
    stock: 1500,
    minOrderQuantity: 10,
    farmerName: 'P. Ramanathan',
    sellerName: 'Nilgiri Spices & Bulbs',
    location: { city: 'Ooty', state: 'Tamil Nadu', lat: 11.4102, lng: 76.6950 },
    harvestDate: '2026-09-25',
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 37,
    image: '/products/p018/image-1.jpg',
    images: [
      '/products/p018/image-1.jpg',
    ],
    gallery: [
      '/products/p018/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_19',
    id: 'prod_19',
    productId: 'p019',
    name: 'Wayanad Fresh Earthy Ginger',
    category: 'Spices',
    description: 'Plump, fiber-rich spicy ginger rhizomes harvested from humid rainforest valleys of Wayanad. High gingerol content.',
    specifications: {
      variety: 'Wayanad Kuruppampadi Bold',
      grade: 'Grade A Fresh Rhizomes',
      gingerolPercentage: '2.4%',
      shelfLife: '20-25 Days',
      packaging: '20 kg ventilated plastic crates',
      organicCertified: true,
      fpoSource: 'Wayanad Organic Spices FPO',
    },
    price: 110,
    unit: 'kg',
    stock: 1800,
    minOrderQuantity: 10,
    farmerName: 'George Joseph',
    sellerName: 'Malabar Spices Consortium',
    location: { city: 'Kalpetta', state: 'Kerala', lat: 11.6050, lng: 76.0830 },
    harvestDate: '2026-10-02',
    quality: 'Grade A',
    rating: 4.9,
    reviewsCount: 51,
    image: '/products/p019/image-1.jpg',
    images: [
      '/products/p019/image-1.jpg',
    ],
    gallery: [
      '/products/p019/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_33',
    id: 'prod_33',
    productId: 'p033',
    name: 'Malabar Black Pepper (Tellicherry Garbled)',
    category: 'Spices',
    description: 'The King of Spices: Extra bold, sun-dried Tellicherry Garbled Special Extra Bold (TGSEB) black peppercorns. Complex woody citrus heat.',
    specifications: {
      variety: 'Tellicherry Garbled Extra Bold TGSEB',
      grade: 'Export Grade 4.75mm+',
      piperinePercentage: '5.2%',
      moistureContent: '10%',
      packaging: '25 kg multi-layer jute export bags',
      organicCertified: true,
      fpoSource: 'Wayanad Hill Spice Farmers Collective',
    },
    price: 680,
    unit: 'kg',
    stock: 950,
    minOrderQuantity: 5,
    farmerName: 'Mathew Varghese',
    sellerName: 'Malabar Coastal Spice Guild',
    location: { city: 'Kozhikode', state: 'Kerala', lat: 11.2588, lng: 75.7804 },
    harvestDate: '2026-09-01',
    quality: 'Export Quality',
    rating: 5.0,
    reviewsCount: 68,
    image: '/products/p033/image-1.jpg',
    images: [
      '/products/p033/image-1.jpg',
    ],
    gallery: [
      '/products/p033/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_34',
    id: 'prod_34',
    productId: 'p034',
    name: 'Idukki Green Cardamom (8mm Bold)',
    category: 'Spices',
    description: 'Lush green, whole 8mm+ jumbo cardamom pods from misty high ranges of Western Ghats. Intense floral eucalyptol fragrance.',
    specifications: {
      variety: 'Mysore Type 8mm Jumbo Green',
      grade: 'Export Grade Special Bold (AGEB)',
      volatileOil: '8.5%',
      moistureContent: '9.5%',
      packaging: '5 kg nitrogen-flushed metallic poly-pouches',
      organicCertified: true,
      fpoSource: 'Cardamom Hills Producers Company',
    },
    price: 2450,
    unit: 'kg',
    stock: 420,
    minOrderQuantity: 1,
    farmerName: 'Joy Sebastian',
    sellerName: 'High Range Spices Consortium',
    location: { city: 'Idukki', state: 'Kerala', lat: 9.8494, lng: 76.9806 },
    harvestDate: '2026-09-12',
    quality: 'Export Quality',
    rating: 5.0,
    reviewsCount: 81,
    image: '/products/p034/image-1.jpg',
    images: [
      '/products/p034/image-1.jpg',
    ],
    gallery: [
      '/products/p034/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },

  // 5. PULSES
  {
    _id: 'prod_14',
    id: 'prod_14',
    productId: 'p014',
    name: 'Black Gram (Split Urad Dal)',
    category: 'Pulses',
    description: 'Unpolished premium black gram split dal. High plant protein, creamy fermentation texture ideal for idli, dosa, and dal makhani.',
    specifications: {
      variety: 'LBG-752 Coastal Andhra Urad',
      grade: 'Unpolished Natural Grade A',
      proteinContent: '24%',
      foreignMatter: '<0.1%',
      packaging: '30 kg PP woven sacks',
      organicCertified: true,
      fpoSource: 'Krishna Pulse Farmers Producer Co.',
    },
    price: 118,
    unit: 'kg',
    stock: 3500,
    minOrderQuantity: 25,
    farmerName: 'T. Subrahmanyam',
    sellerName: 'Andhra Dal Millers Union',
    location: { city: 'Tenali', state: 'Andhra Pradesh', lat: 16.2437, lng: 80.6400 },
    harvestDate: '2026-09-10',
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 41,
    image: '/products/p014/image-1.jpg',
    images: [
      '/products/p014/image-1.jpg',
    ],
    gallery: [
      '/products/p014/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_15',
    id: 'prod_15',
    productId: 'p015',
    name: 'Green Gram (Whole Moong Dal)',
    category: 'Pulses',
    description: 'Small, glossy whole green moong beans. Uniform germination, rich in dietary fiber and essential plant protein with zero polish.',
    specifications: {
      variety: 'IPM 02-3 Pusa Vishal',
      grade: 'Grade A Unpolished',
      proteinContent: '24.2%',
      germinationRate: '96% for sprouting',
      packaging: '25 kg PP bags',
      organicCertified: true,
      fpoSource: 'Chambal Bio-Pulse Producer Co.',
    },
    price: 105,
    unit: 'kg',
    stock: 2900,
    minOrderQuantity: 20,
    farmerName: 'Devendra Meena',
    sellerName: 'Rajasthan Krishi Syndicate',
    location: { city: 'Kota', state: 'Rajasthan', lat: 25.2138, lng: 75.8648 },
    harvestDate: '2026-09-14',
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 38,
    image: '/products/p015/image-1.jpg',
    images: [
      '/products/p015/image-1.jpg',
    ],
    gallery: [
      '/products/p015/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_16',
    id: 'prod_16',
    productId: 'p016',
    name: 'Bengal Gram (Desi Chana Dal)',
    category: 'Pulses',
    description: 'Clean sorted desi chana split gram. Golden nutty taste, zero chemical additives or artificial food coloring.',
    specifications: {
      variety: 'JG-11 Desi Yellow Gram',
      grade: 'Grade A Unpolished',
      proteinContent: '22.5%',
      moistureContent: '10%',
      packaging: '50 kg food-grade bags',
      organicCertified: false,
      fpoSource: 'Marathwada Gram Farmers Alliance',
    },
    price: 78,
    unit: 'kg',
    stock: 4800,
    minOrderQuantity: 50,
    farmerName: 'Govind Jadhav',
    sellerName: 'Latur Pulse Hub',
    location: { city: 'Latur', state: 'Maharashtra', lat: 18.4088, lng: 76.5604 },
    harvestDate: '2026-09-05',
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 57,
    image: '/products/p016/image-1.jpg',
    images: [
      '/products/p016/image-1.jpg',
    ],
    gallery: [
      '/products/p016/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_35',
    id: 'prod_35',
    productId: 'p035',
    name: 'Gulbarga Organic Toor Dal (Arhar Dal)',
    category: 'Pulses',
    description: 'GI tagged Kalaburagi Red Gram. Exceptional sweetness, rapid cooking time, completely chemical unpolished split pigeon peas.',
    specifications: {
      variety: 'Gulbarga Red Gram GI Tag',
      grade: 'Certified Organic Premium',
      proteinContent: '23.8%',
      cookingTime: '20-25 mins (no baking soda needed)',
      packaging: '25 kg multi-wall eco paper-plastic bags',
      organicCertified: true,
      fpoSource: 'Kalaburagi Red Gram Growers Guild',
    },
    price: 155,
    unit: 'kg',
    stock: 3800,
    minOrderQuantity: 25,
    farmerName: 'Mallikarjun Patil',
    sellerName: 'Kalyana Karnataka Pulse Syndicate',
    location: { city: 'Kalaburagi', state: 'Karnataka', lat: 17.3297, lng: 76.8343 },
    harvestDate: '2026-09-20',
    quality: 'Organic Certified',
    rating: 4.9,
    reviewsCount: 63,
    image: '/products/p035/image-1.jpg',
    images: [
      '/products/p035/image-1.jpg',
    ],
    gallery: [
      '/products/p035/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },

  // 6. OIL SEEDS
  {
    _id: 'prod_11',
    id: 'prod_11',
    productId: 'p011',
    name: 'Bold Raw Groundnuts (Peanuts)',
    category: 'Oil Seeds',
    description: 'Thick-shelled bold groundnut kernels. High oil yield (48%), sweet taste, zero aflatoxin tested for premium peanut butter or oil extraction.',
    specifications: {
      variety: 'TAG-24 Saurashtra Bold',
      grade: 'Grade A Oil Grade',
      oilContent: '48.5%',
      moistureContent: '7%',
      packaging: '50 kg breathable gunny sacks',
      organicCertified: false,
      fpoSource: 'Junagadh Oilseeds Farmers Society',
    },
    price: 88,
    unit: 'kg',
    stock: 6200,
    minOrderQuantity: 50,
    farmerName: 'Hasmukhbhai Patel',
    sellerName: 'Saurashtra Agro Oilseeds',
    location: { city: 'Rajkot', state: 'Gujarat', lat: 22.3039, lng: 70.8022 },
    harvestDate: '2026-09-24',
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 49,
    image: '/products/p011/image-1.jpg',
    images: [
      '/products/p011/image-1.jpg',
    ],
    gallery: [
      '/products/p011/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_36',
    id: 'prod_36',
    productId: 'p036',
    name: 'Rajasthan Yellow Mustard Seeds',
    category: 'Oil Seeds',
    description: 'Bold yellow sarson mustard seeds from mustard heartland of Bharatpur. High cold-press pungent kachi ghani oil recovery (41%).',
    specifications: {
      variety: 'Pusa Bold Yellow Sarson',
      grade: 'Grade A Cold-Press Quality',
      oilContent: '41.5%',
      purity: '99.5%',
      packaging: '50 kg laminated HDPE bags',
      organicCertified: true,
      fpoSource: 'Bharatpur Mustard Producers Union',
    },
    price: 72,
    unit: 'kg',
    stock: 5800,
    minOrderQuantity: 50,
    farmerName: 'Ramkishan Saini',
    sellerName: 'Brij Oilseed Traders',
    location: { city: 'Bharatpur', state: 'Rajasthan', lat: 27.2152, lng: 77.4930 },
    harvestDate: '2026-09-19',
    quality: 'Organic Certified',
    rating: 4.8,
    reviewsCount: 35,
    image: '/products/p036/image-1.jpg',
    images: [
      '/products/p036/image-1.jpg',
    ],
    gallery: [
      '/products/p036/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },

  // 7. OTHER AGRICULTURAL PRODUCTS
  {
    _id: 'prod_13',
    id: 'prod_13',
    productId: 'p013',
    name: 'Shankar-6 Raw Cotton Bolls',
    category: 'Other Agricultural Products',
    description: 'World-standard medium to long staple Shankar-6 white raw cotton with minimal seed trash and high micronaire fineness.',
    specifications: {
      variety: 'Gujarat Shankar-6 (S-6)',
      grade: 'Export Grade Raw Seed Cotton',
      stapleLength: '28-29 mm',
      micronaire: '3.8-4.2',
      packaging: '170 kg hydraulic compressed bales',
      organicCertified: false,
      fpoSource: 'Kadi Cotton Growers Cooperative',
    },
    price: 74,
    unit: 'kg',
    stock: 12000,
    minOrderQuantity: 200,
    farmerName: 'Dineshbhai Patel',
    sellerName: 'Gujarat Cotton Ginning Guild',
    location: { city: 'Kadi', state: 'Gujarat', lat: 23.2980, lng: 72.3320 },
    harvestDate: '2026-09-28',
    quality: 'Export Quality',
    rating: 4.8,
    reviewsCount: 58,
    image: '/products/p013/image-1.jpg',
    images: [
      '/products/p013/image-1.jpg',
    ],
    gallery: [
      '/products/p013/image-1.jpg',
    ],
    video: null,
    isOrganic: false,
    isFeatured: false,
    isApproved: true,
    createdAt: new Date(),
  },
  {
    _id: 'prod_37',
    id: 'prod_37',
    productId: 'p037',
    name: 'Natural Kolhapur Sugarcane Jaggery (Gur)',
    category: 'Other Agricultural Products',
    description: 'Pure, chemical-free sugarcane jaggery prepared using traditional wild okra mucilage clarification. High natural minerals, zero sulfur dioxide.',
    specifications: {
      variety: 'Kolhapur Traditional Gur GI Tag',
      grade: 'Grade A Chemical-Free',
      sucroseContent: '82%',
      sulfurDioxide: '0.00% (No artificial sodium hydrosulfite)',
      packaging: '1 kg & 5 kg traditional round bucket molds',
      organicCertified: true,
      fpoSource: 'Panchaganga River Valley Gur FPO',
    },
    price: 62,
    unit: 'kg',
    stock: 4500,
    minOrderQuantity: 20,
    farmerName: 'Hanumantrao Patil',
    sellerName: 'Kolhapur Mandi Gur Syndicate',
    location: { city: 'Kolhapur', state: 'Maharashtra', lat: 16.7050, lng: 74.2433 },
    harvestDate: '2026-09-26',
    quality: 'Organic Certified',
    rating: 4.9,
    reviewsCount: 73,
    image: '/products/p037/image-1.jpg',
    images: [
      '/products/p037/image-1.jpg',
    ],
    gallery: [
      '/products/p037/image-1.jpg',
    ],
    video: null,
    isOrganic: true,
    isFeatured: true,
    isApproved: true,
    createdAt: new Date(),
  },
];

/**
 * Strict Media Validation Function
 */
export function validateProductMedia(products = masterProductCatalog) {
  const errors = [];
  const seenIds = new Set();
  const seenUrls = new Map();

  products.forEach((p) => {
    if (!p._id || !p.productId) {
      errors.push(`❌ Product missing ID: "${p.name}"`);
    } else if (seenIds.has(p._id)) {
      errors.push(`❌ Duplicate Product ID: "${p._id}" ("${p.name}")`);
    } else {
      seenIds.add(p._id);
    }

    if (!p.images || p.images.length === 0) {
      errors.push(`❌ Product "${p.name}" (${p._id}) has no product-specific images`);
    }

    const allImages = [p.image, ...(p.images || [])].filter(Boolean);
    allImages.forEach((url) => {
      if (seenUrls.has(url)) {
        const prev = seenUrls.get(url);
        if (prev.id !== p._id) {
          errors.push(
            `❌ Cross-product image reuse: URL "${url.slice(0, 45)}..." assigned to both "${prev.id}: ${prev.name}" and "${p._id}: ${p.name}"`
          );
        }
      } else {
        seenUrls.set(url, { id: p._id, name: p.name });
      }
    });
  });

  return {
    valid: errors.length === 0,
    errors,
    crossReusedCount: errors.filter((e) => e.includes('Cross-product image reuse')).length,
    totalProducts: products.length,
  };
}
