import bcrypt from 'bcryptjs';
import { masterProductCatalog } from './productCatalog.js';

// Pre-seeded local cache for 100% resilience with comprehensive big data
export const createResilientStore = () => {
  const salt = bcrypt.genSaltSync(10);
  const hash = bcrypt.hashSync('AgriTrade@2026', salt);
  const adminHash = bcrypt.hashSync('password@123', salt);

  const users = [
    {
      _id: '6ac70ae8bdce7a50b745e1a7',
      id: '6ac70ae8bdce7a50b745e1a7',
      name: 'Kasani Manikanta',
      email: 'kasanimanikanta2005@gmail.com',
      phone: '+91 99123 45678',
      password: adminHash,
      role: 'admin',
      organization: 'AgriTrade Hub AI National Mission',
      location: { city: 'Hyderabad', state: 'Telangana' },
      isApproved: true,
    },
    {
      _id: '670000000000000000000002',
      id: '670000000000000000000002',
      name: 'Ramesh Reddy',
      email: 'farmer.ramesh@agritradehub.ai',
      phone: '+91 98481 22334',
      password: hash,
      role: 'farmer',
      organization: 'Guntur Kisan Producers Cooperative',
      location: { city: 'Guntur', state: 'Andhra Pradesh' },
      isApproved: true,
    },
    {
      _id: '670000000000000000000003',
      id: '670000000000000000000003',
      name: 'Suresh Kumar Trading',
      email: 'seller.suresh@agritradehub.ai',
      phone: '+91 98483 44556',
      password: hash,
      role: 'seller',
      organization: 'Guntur Spice Merchants Association',
      location: { city: 'Guntur', state: 'Andhra Pradesh' },
      isApproved: true,
    },
    {
      _id: '670000000000000000000004',
      id: '670000000000000000000004',
      name: 'Anita Sharma',
      email: 'consumer.anita@agritradehub.ai',
      phone: '+91 98484 55667',
      password: hash,
      role: 'consumer',
      organization: 'Household Consumer',
      location: { city: 'Bengaluru', state: 'Karnataka' },
      isApproved: true,
    },
    {
      _id: '670000000000000000000005',
      id: '670000000000000000000005',
      name: 'Reliance Retail Agritech Hub',
      email: 'buyer.reliance@agritradehub.ai',
      phone: '+91 98485 66778',
      password: hash,
      role: 'buyer',
      organization: 'Reliance Retail Ventures Ltd',
      location: { city: 'Mumbai', state: 'Maharashtra' },
      isApproved: true,
    },
    {
      _id: '670000000000000000000006',
      id: '670000000000000000000006',
      name: 'Balasaheb Patil',
      email: 'farmer.balasaheb@agritradehub.ai',
      phone: '+91 98220 11982',
      password: hash,
      role: 'farmer',
      organization: 'Nashik Onion Growers FPO',
      location: { city: 'Nashik', state: 'Maharashtra' },
      isApproved: true,
    },
    {
      _id: '670000000000000000000007',
      id: '670000000000000000000007',
      name: 'ITC Agri-Business Division',
      email: 'buyer.itc@agritradehub.ai',
      phone: '+91 33228 89300',
      password: hash,
      role: 'buyer',
      organization: 'ITC Limited - e-Choupal',
      location: { city: 'Kolkata', state: 'West Bengal' },
      isApproved: true,
    },
    {
      _id: '670000000000000000000008',
      id: '670000000000000000000008',
      name: 'Gurpreet Singh',
      email: 'farmer.gurpreet@agritradehub.ai',
      phone: '+91 98140 77210',
      password: hash,
      role: 'farmer',
      organization: 'Majha Basmati Producers Guild',
      location: { city: 'Amritsar', state: 'Punjab' },
      isApproved: true,
    },
    {
      _id: '670000000000000000000009',
      id: '670000000000000000000009',
      name: 'BigBasket Supply Central',
      email: 'buyer.bigbasket@agritradehub.ai',
      phone: '+91 80682 99000',
      password: hash,
      role: 'buyer',
      organization: 'Supermarket Grocery Supplies',
      location: { city: 'Bengaluru', state: 'Karnataka' },
      isApproved: true,
    },
    {
      _id: '670000000000000000000010',
      id: '670000000000000000000010',
      name: 'Maharashtra Krishi Vyapar',
      email: 'seller.krishi@agritradehub.ai',
      phone: '+91 25327 88120',
      password: hash,
      role: 'seller',
      organization: 'Lasalgaon APMC Merchant Guild',
      location: { city: 'Nashik', state: 'Maharashtra' },
      isApproved: true,
    }
  ];

  // 35 fully verified products with strict unique product-specific media
  const products = JSON.parse(JSON.stringify(masterProductCatalog));

  const requirements = [
    {
      _id: 'demand_01',
      tenderId: 'TNDR-ITC-2026-981',
      buyerName: 'ITC Agri-Business Division',
      buyerEmail: 'procure.wheat@itc.in',
      buyerPhone: '+91 33228 89300',
      productName: 'MP Sharbati Golden Wheat (Aashirvaad Grade)',
      category: 'Grains',
      quantity: 2500,
      unit: 'Tonnes',
      maxPricePerUnit: 42,
      targetLocation: 'ITC Flours Factory, Malanpur Industrial Area, MP',
      targetDate: new Date('2026-10-25'),
      status: 'OPEN_FOR_BIDS',
      createdAt: new Date(),
    },
    {
      _id: 'demand_02',
      tenderId: 'TNDR-REL-2026-442',
      buyerName: 'Reliance Retail Fresh Hub',
      buyerEmail: 'procurement.fresh@relretail.com',
      buyerPhone: '+91 22447 70000',
      productName: 'Nasik Red Onions (Medium-Large Grade)',
      category: 'Vegetables',
      quantity: 1800,
      unit: 'Tonnes',
      maxPricePerUnit: 28,
      targetLocation: 'Reliance Fresh Central DC, Bhiwandi, MH',
      targetDate: new Date('2026-10-20'),
      status: 'OPEN_FOR_BIDS',
      createdAt: new Date(),
    },
    {
      _id: 'demand_03',
      tenderId: 'TNDR-BB-2026-118',
      buyerName: 'BigBasket Fresh Farm Direct Hub',
      buyerEmail: 'farmerconnect@bigbasket.com',
      buyerPhone: '+91 80682 99000',
      productName: 'Fresh Farm Vine Tomatoes (Hybrid Grade A)',
      category: 'Vegetables',
      quantity: 650,
      unit: 'Tonnes',
      maxPricePerUnit: 32,
      targetLocation: 'BigBasket Tier-1 DC, Whitefield, Bangalore, KA',
      targetDate: new Date('2026-10-18'),
      status: 'OPEN_FOR_BIDS',
      createdAt: new Date(),
    },
    {
      _id: 'demand_04',
      tenderId: 'TNDR-MDH-2026-559',
      buyerName: 'MDH Spices Raw Materials Division',
      buyerEmail: 'purchase.spices@mdhspices.in',
      buyerPhone: '+91 11255 08800',
      productName: 'Guntur Teja S17 Dried Red Chillies',
      category: 'Spices',
      quantity: 400,
      unit: 'Tonnes',
      maxPricePerUnit: 220,
      targetLocation: 'MDH Processing Mill, Delhi NCR',
      targetDate: new Date('2026-11-05'),
      status: 'OPEN_FOR_BIDS',
      createdAt: new Date(),
    }
  ];

  const orders = [
    {
      _id: 'order_seed_01',
      orderId: 'AGRI-982143-2026',
      customerName: 'Anita Sharma',
      customerEmail: 'consumer.anita@agritradehub.ai',
      customerPhone: '+91 98484 55667',
      shippingAddress: {
        street: 'Flat 402, Green Meadows, Gachibowli',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500032',
        country: 'India',
      },
      items: [
        {
          product: 'prod_01',
          name: 'Fresh Farm Tomatoes',
          price: 32,
          quantity: 25,
          unit: 'kg',
          image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
          subtotal: 800,
        },
        {
          product: 'prod_02',
          name: 'Nasik Red Onions',
          price: 28,
          quantity: 30,
          unit: 'kg',
          image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=80',
          subtotal: 840,
        },
      ],
      subtotal: 1640,
      deliveryFee: 0,
      discount: 0,
      total: 1640,
      paymentMethod: 'Razorpay Sandbox',
      paymentStatus: 'paid',
      orderStatus: 'out_for_delivery',
      estimatedDelivery: new Date(Date.now() + 24 * 3600 * 1000),
      trackingHistory: [
        { status: 'confirmed', note: 'Order registered in dispatch queue', timestamp: new Date(Date.now() - 36 * 3600 * 1000) },
        { status: 'packed', note: 'Packed in ventilated crates at Guntur Hub', timestamp: new Date(Date.now() - 18 * 3600 * 1000) },
        { status: 'dispatched', note: 'Cold transit reefer en route to Hyderabad', timestamp: new Date(Date.now() - 6 * 3600 * 1000) },
        { status: 'out_for_delivery', note: 'Out for final doorstep handover', timestamp: new Date() },
      ],
      customerEmailSent: true,
      adminEmailSent: true,
      createdAt: new Date(Date.now() - 36 * 3600 * 1000),
    },
    {
      _id: 'order_seed_02',
      orderId: 'AGRI-773190-2026',
      customerName: 'Reliance Retail Fresh Hub',
      customerEmail: 'buyer.reliance@agritradehub.ai',
      customerPhone: '+91 98485 66778',
      shippingAddress: {
        street: 'Central DC, Gate 4, Bhiwandi Logistics Park',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '421302',
        country: 'India',
      },
      items: [
        {
          product: 'prod_08',
          name: 'Guntur Teja Red Chillies',
          price: 220,
          quantity: 200,
          unit: 'kg',
          image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=800&q=80',
          subtotal: 44000,
        },
      ],
      subtotal: 44000,
      deliveryFee: 1200,
      discount: 0,
      total: 45200,
      paymentMethod: 'Bank Escrow Transfer',
      paymentStatus: 'paid',
      orderStatus: 'dispatched',
      estimatedDelivery: new Date(Date.now() + 48 * 3600 * 1000),
      trackingHistory: [
        { status: 'confirmed', note: 'Institutional purchase order locked', timestamp: new Date(Date.now() - 24 * 3600 * 1000) },
        { status: 'dispatched', note: 'Loaded onto 14T reefer container (AP39-TE-8812)', timestamp: new Date(Date.now() - 4 * 3600 * 1000) }
      ],
      customerEmailSent: true,
      adminEmailSent: true,
      createdAt: new Date(Date.now() - 24 * 3600 * 1000),
    }
  ];

  const emailLogs = [
    {
      _id: 'log_01',
      recipient: 'kasanimanikanta2005@gmail.com',
      subject: 'AgriTrade Hub AI - Security Login OTP',
      type: 'OTP_VERIFICATION',
      status: 'SENT',
      messageId: '<otp-verification-98210@mail.agritradehub.ai>',
      timestamp: new Date(Date.now() - 10 * 60 * 1000),
    },
    {
      _id: 'log_02',
      recipient: 'consumer.anita@agritradehub.ai',
      subject: 'Order Confirmation #AGRI-982143-2026',
      type: 'ORDER_CONFIRMATION',
      status: 'SENT',
      messageId: '<order-dispatch-7712@mail.agritradehub.ai>',
      timestamp: new Date(Date.now() - 36 * 3600 * 1000),
    }
  ];

  const lastSync = {
    syncId: `SYNC-${Date.now()}`,
    startedAt: new Date(Date.now() - 5 * 60 * 1000),
    completedAt: new Date(Date.now() - 4 * 60 * 1000),
    status: 'SUCCESS',
    sheetsUpdated: 8,
    rowsUpdated: 52,
    rowsAdded: 0,
    rowsFailed: 0,
    admin: 'kasanimanikanta2005@gmail.com',
    datasets: ['Users', 'Farmers', 'Sellers', 'Consumers', 'Bulk Buyers', 'Products', 'Orders', 'Email Logs'],
    spreadsheetId: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    spreadsheetUrl: 'https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit',
  };

  const syncAudits = [
    {
      _id: 'audit_01',
      syncId: lastSync.syncId,
      startedAt: lastSync.startedAt,
      completedAt: lastSync.completedAt,
      admin: lastSync.admin,
      source: 'AgriTrade Hub Database',
      sheetsUpdated: 8,
      rowsUpdated: 52,
      rowsAdded: 0,
      rowsFailed: 0,
      status: 'SUCCESS',
      datasets: lastSync.datasets,
      spreadsheetId: lastSync.spreadsheetId,
      spreadsheetUrl: lastSync.spreadsheetUrl,
    }
  ];

  return { users, products, requirements, orders, emailLogs, lastSync, syncAudits };
};

export const resilientStore = createResilientStore();
