import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
import User from '../models/User.js';
import Product from '../models/Product.js';
import Order from '../models/Order.js';
import BuyerRequirement from '../models/BuyerRequirement.js';
import Review from '../models/Review.js';
import { masterProductCatalog } from './productCatalog.js';

dotenv.config();

const PRODUCTS_DATA = [
  {
    name: 'Fresh Farm Tomatoes',
    category: 'Vegetables',
    description: 'Vine-ripened, naturally cultivated Grade A hybrid tomatoes with firm texture and high lycopene content. Ideal for salads, curries, and processing.',
    price: 32,
    unit: 'kg',
    stock: 2500,
    minOrderQuantity: 5,
    farmerName: 'Ramesh Reddy (Kisan Samiti)',
    sellerName: 'Guntur Vegetable Hub',
    location: { city: 'Guntur', state: 'Andhra Pradesh', lat: 16.3067, lng: 80.4365 },
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 38,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: true,
  },
  {
    name: 'Nasik Red Onions',
    category: 'Vegetables',
    description: 'Medium to large pungent red onions directly harvested from Nasik fertile soils. Excellent shelf life, moisture-balanced, cured under sun.',
    price: 28,
    unit: 'kg',
    stock: 4500,
    minOrderQuantity: 10,
    farmerName: 'Balasaheb Patil',
    sellerName: 'Maharashtra Krishi Vyapar',
    location: { city: 'Nashik', state: 'Maharashtra', lat: 19.9975, lng: 73.7898 },
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 54,
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=80',
    isOrganic: false,
    isFeatured: true,
  },
  {
    name: 'Agra Jyoti Potatoes',
    category: 'Vegetables',
    description: 'Thin-skinned, starch-rich high quality table potatoes. Clean washed, zero greening, uniform sizing for household and commercial kitchens.',
    price: 22,
    unit: 'kg',
    stock: 6000,
    minOrderQuantity: 10,
    farmerName: 'Suresh Kumar Yadav',
    sellerName: 'Yamuna Agri Traders',
    location: { city: 'Agra', state: 'Uttar Pradesh', lat: 27.1767, lng: 78.0081 },
    quality: 'Grade A',
    rating: 4.6,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
    isOrganic: false,
    isFeatured: true,
  },
  {
    name: 'Banganapalli Golden Mangoes',
    category: 'Fruits',
    description: 'Geographical Indication (GI) tagged royal sweet mangoes. Fiberless pulp, thin golden skin, naturally ripened without carbide.',
    price: 130,
    unit: 'kg',
    stock: 1200,
    minOrderQuantity: 5,
    farmerName: 'Venkat Rao Orchards',
    sellerName: 'Rayalaseema Fruit FPO',
    location: { city: 'Kurnool', state: 'Andhra Pradesh', lat: 15.8281, lng: 78.0373 },
    quality: 'Export Quality',
    rating: 4.9,
    reviewsCount: 78,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: true,
  },
  {
    name: 'Robusta Golden Bananas',
    category: 'Fruits',
    description: 'Sweet, energy-rich unblemished Robusta bananas harvested fresh from Cauvery delta groves. Controlled ripening, high potassium content.',
    price: 45,
    unit: 'kg',
    stock: 1800,
    minOrderQuantity: 5,
    farmerName: 'Murugan Thottam',
    sellerName: 'Tamil Nadu Banana Growers',
    location: { city: 'Tiruchirappalli', state: 'Tamil Nadu', lat: 10.7905, lng: 78.7047 },
    quality: 'Grade A+',
    rating: 4.7,
    reviewsCount: 31,
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: true,
  },
  {
    name: 'Aromatic Basmati Rice (1121)',
    category: 'Grains',
    description: 'Premium aged extra-long slender basmati grain. Exceptional aroma, cooks up to 2.5 times its length with separate fluffy grains.',
    price: 95,
    unit: 'kg',
    stock: 5000,
    minOrderQuantity: 25,
    farmerName: 'Gurpreet Singh',
    sellerName: 'Punjab Agro Exports',
    location: { city: 'Amritsar', state: 'Punjab', lat: 31.6340, lng: 74.8723 },
    quality: 'Export Quality',
    rating: 4.9,
    reviewsCount: 65,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
    isOrganic: false,
    isFeatured: true,
  },
  {
    name: 'MP Sharbati Golden Wheat',
    category: 'Grains',
    description: 'Known as the King of Wheat from the black soils of Sehore. Heavy luster, sweet dough taste, naturally enriched with zinc and iron.',
    price: 42,
    unit: 'kg',
    stock: 7500,
    minOrderQuantity: 50,
    farmerName: 'Anand Sharma',
    sellerName: 'Narmada Grain Syndicate',
    location: { city: 'Bhopal', state: 'Madhya Pradesh', lat: 23.2599, lng: 77.4126 },
    quality: 'Grade A',
    rating: 4.8,
    reviewsCount: 49,
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: true,
  },
  {
    name: 'Guntur Teja Red Chillies',
    category: 'Spices',
    description: 'Fiery hot, intense red dried chillies world-famous from Asia largest chilli market. High SHU capsaicin, deep color, moisture under 10%.',
    price: 220,
    unit: 'kg',
    stock: 3200,
    minOrderQuantity: 10,
    farmerName: 'Koteswara Rao',
    sellerName: 'Guntur Spice Merchants Association',
    location: { city: 'Guntur', state: 'Andhra Pradesh', lat: 16.3067, lng: 80.4365 },
    quality: 'Export Quality',
    rating: 4.9,
    reviewsCount: 92,
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=800&q=80',
    isOrganic: false,
    isFeatured: true,
  },
  {
    name: 'Fresh Pungent Green Chillies',
    category: 'Vegetables',
    description: 'Crisp, spicy green chillies handpicked fresh at dawn. Glossy skin, ideal pungency for culinary applications and food service.',
    price: 48,
    unit: 'kg',
    stock: 900,
    minOrderQuantity: 5,
    farmerName: 'Santosh Gowda',
    sellerName: 'Kolar Horticultural Collective',
    location: { city: 'Kolar', state: 'Karnataka', lat: 13.1367, lng: 78.1291 },
    quality: 'Grade A',
    rating: 4.6,
    reviewsCount: 22,
    image: 'https://images.unsplash.com/photo-1563865436874-9aef32095fad?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: false,
  },
  {
    name: 'Lakadong High-Curcumin Turmeric',
    category: 'Spices',
    description: 'World-renowned turmeric with over 7.5% natural curcumin content. Intense aromatic earthy flavor, vivid deep orange-gold hue, sun cured.',
    price: 180,
    unit: 'kg',
    stock: 1400,
    minOrderQuantity: 5,
    farmerName: 'Lakhon Warjri',
    sellerName: 'Jaintia Organic Hills FPO',
    location: { city: 'Shillong', state: 'Meghalaya', lat: 25.5788, lng: 91.8933 },
    quality: 'Organic Certified',
    rating: 5.0,
    reviewsCount: 46,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: true,
  },
  {
    name: 'Bold Raw Groundnuts (Peanuts)',
    category: 'Oil Seeds',
    description: 'Unshelled dry pods and clean kernels with high oil recovery (48%+). Freshly decorticated, sweet natural taste, aflatoxin tested negative.',
    price: 90,
    unit: 'kg',
    stock: 4200,
    minOrderQuantity: 20,
    farmerName: 'Bhavani Shankar',
    sellerName: 'Saurashtra Oilseed Traders',
    location: { city: 'Rajkot', state: 'Gujarat', lat: 22.3039, lng: 70.8022 },
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 28,
    image: 'https://images.unsplash.com/photo-1567894340315-735d7c361db0?auto=format&fit=crop&w=800&q=80',
    isOrganic: false,
    isFeatured: false,
  },
  {
    name: 'Golden Yellow Maize / Corn',
    category: 'Grains',
    description: 'Clean dry yellow maize kernels with moisture below 13%. Excellent bulk commodity for cattle feed, poultry feed, and corn starch manufacturing.',
    price: 24,
    unit: 'kg',
    stock: 8000,
    minOrderQuantity: 100,
    farmerName: 'Mallikarjun Biradar',
    sellerName: 'Davangere Agro Mandi',
    location: { city: 'Davangere', state: 'Karnataka', lat: 14.4644, lng: 75.9218 },
    quality: 'Grade A',
    rating: 4.5,
    reviewsCount: 19,
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=800&q=80',
    isOrganic: false,
    isFeatured: false,
  },
  {
    name: 'Shankar-6 Raw Cotton Bolls',
    category: 'Other Agricultural Products',
    description: 'Long staple Shankar-6 premium cotton. Clean white bolls with high tensile strength and minimal trash content, ginning ready.',
    price: 85,
    unit: 'kg',
    stock: 9500,
    minOrderQuantity: 100,
    farmerName: 'Kishore Bhai Patel',
    sellerName: 'Gujarat Cotton Federation',
    location: { city: 'Surendranagar', state: 'Gujarat', lat: 22.7275, lng: 71.6375 },
    quality: 'Export Quality',
    rating: 4.8,
    reviewsCount: 35,
    image: 'https://images.unsplash.com/photo-1606041008023-472dfb5e530f?auto=format&fit=crop&w=800&q=80',
    isOrganic: false,
    isFeatured: false,
  },
  {
    name: 'Black Gram (Split Urad Dal)',
    category: 'Pulses',
    description: 'Unpolished premium black gram split dal. High plant protein, essential for south Indian batters, zero artificial coloring or talc polishing.',
    price: 110,
    unit: 'kg',
    stock: 3100,
    minOrderQuantity: 15,
    farmerName: 'Venkatesh Naidu',
    sellerName: 'Krishna Valley Pulses',
    location: { city: 'Vijayawada', state: 'Andhra Pradesh', lat: 16.5062, lng: 80.6480 },
    quality: 'Grade A+',
    rating: 4.8,
    reviewsCount: 37,
    image: 'https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: false,
  },
  {
    name: 'Green Gram (Whole Moong Dal)',
    category: 'Pulses',
    description: 'Whole organic green gram beans. Uniform grain size, high germination rate for sprouting, rich in dietary fiber and essential minerals.',
    price: 105,
    unit: 'kg',
    stock: 2800,
    minOrderQuantity: 15,
    farmerName: 'Sunita Devi Deshmukh',
    sellerName: 'Latur Agro Market Exchange',
    location: { city: 'Latur', state: 'Maharashtra', lat: 18.4088, lng: 76.5604 },
    quality: 'Organic Certified',
    rating: 4.9,
    reviewsCount: 44,
    image: 'https://images.unsplash.com/photo-1612255109949-a86fad294ba5?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: false,
  },
  {
    name: 'Bengal Gram (Desi Chana Dal)',
    category: 'Pulses',
    description: 'Sun-dried high-grade yellow split chickpeas. Distinct nutty aroma, firm bite, clean machine-sorted free from broken husks.',
    price: 78,
    unit: 'kg',
    stock: 3800,
    minOrderQuantity: 20,
    farmerName: 'Radheshyam Gupta',
    sellerName: 'Indore Mandi Dal Millers',
    location: { city: 'Indore', state: 'Madhya Pradesh', lat: 22.7196, lng: 75.8577 },
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 29,
    image: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=800&q=80',
    isOrganic: false,
    isFeatured: false,
  },
  {
    name: 'Fresh Leafy Coriander Bunches',
    category: 'Vegetables',
    description: 'Aromatic tender green coriander with vibrant fragrance and deep green leaves. Cut fresh daily with root intact for maximum freshness.',
    price: 35,
    unit: 'kg',
    stock: 650,
    minOrderQuantity: 3,
    farmerName: 'Anil Kumar Gaikwad',
    sellerName: 'Pune Fresh Direct',
    location: { city: 'Pune', state: 'Maharashtra', lat: 18.5204, lng: 73.8567 },
    quality: 'Grade A',
    rating: 4.6,
    reviewsCount: 18,
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: false,
  },
  {
    name: 'Ooty White Garlic Bulbs',
    category: 'Spices',
    description: 'Hill-grown large white garlic bulbs with tight skins and pungent cloves. Excellent medicinal allicin yield and durable ambient storage.',
    price: 160,
    unit: 'kg',
    stock: 1900,
    minOrderQuantity: 5,
    farmerName: 'Subramanian Nilgiris',
    sellerName: 'Ooty Spices & Herbs FPO',
    location: { city: 'Ooty', state: 'Tamil Nadu', lat: 11.4102, lng: 76.6950 },
    quality: 'Grade A+',
    rating: 4.9,
    reviewsCount: 51,
    image: 'https://images.unsplash.com/photo-1615478443916-2c6b4121bf66?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: true,
  },
  {
    name: 'Wayanad Fresh Earthy Ginger',
    category: 'Spices',
    description: 'Plump fibrous aromatic ginger fingers freshly harvested from rain-washed Wayanad estates. Potent essential oil, wash-cleaned and dried.',
    price: 120,
    unit: 'kg',
    stock: 1600,
    minOrderQuantity: 5,
    farmerName: 'Thomas Mathew',
    sellerName: 'Kerala Spices Consortium',
    location: { city: 'Wayanad', state: 'Kerala', lat: 11.6854, lng: 76.1320 },
    quality: 'Export Quality',
    rating: 4.8,
    reviewsCount: 39,
    image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: false,
  },
  {
    name: 'Crunchy Orange Carrots',
    category: 'Vegetables',
    description: 'Sweet, crisp, beta-carotene rich deep orange carrots. Machine washed and graded, uniform taper, tender juicy core.',
    price: 36,
    unit: 'kg',
    stock: 2200,
    minOrderQuantity: 5,
    farmerName: 'Jagjit Sandhu',
    sellerName: 'Hoshiarpur Cold Chain Logistics',
    location: { city: 'Hoshiarpur', state: 'Punjab', lat: 31.5273, lng: 75.9149 },
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 26,
    image: 'https://images.unsplash.com/photo-1447175008436-054170c2e979?auto=format&fit=crop&w=800&q=80',
    isOrganic: false,
    isFeatured: false,
  },
  {
    name: 'Purple Glossy Brinjal (Eggplant)',
    category: 'Vegetables',
    description: 'Glossy dark purple teardrop eggplants with minimal seed cavity. Tender flesh, zero pest damage, harvested in cold morning hours.',
    price: 30,
    unit: 'kg',
    stock: 1400,
    minOrderQuantity: 5,
    farmerName: 'Prabhakar Rao',
    sellerName: 'Warangal Krishi Mandi',
    location: { city: 'Warangal', state: 'Telangana', lat: 17.9689, lng: 79.5941 },
    quality: 'Grade A',
    rating: 4.6,
    reviewsCount: 21,
    image: 'https://images.unsplash.com/photo-1628773822503-930a8451f28b?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: false,
  },
  {
    name: 'Tender Green Okra (Bhindi)',
    category: 'Vegetables',
    description: 'Slender, tender, fiber-free fresh green ladyfingers. Snaps cleanly with zero woodiness, high mucilage content for authentic cooking.',
    price: 40,
    unit: 'kg',
    stock: 1300,
    minOrderQuantity: 5,
    farmerName: 'Narayana Swamy',
    sellerName: 'Chittoor Vegetable Aggregation',
    location: { city: 'Chittoor', state: 'Andhra Pradesh', lat: 13.2172, lng: 79.1003 },
    quality: 'Grade A',
    rating: 4.7,
    reviewsCount: 33,
    image: 'https://images.unsplash.com/photo-1525607551316-4a8e16d1f9ba?auto=format&fit=crop&w=800&q=80',
    isOrganic: true,
    isFeatured: true,
  },
];

export const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('[Seed] Connected to MongoDB Atlas');

    // Clean existing seed collections
    await User.deleteMany({ email: { $regex: /@agritradehub\.ai|demo/ } });
    await Product.deleteMany({});
    await Order.deleteMany({});
    await BuyerRequirement.deleteMany({});
    await Review.deleteMany({});

    console.log('[Seed] Cleared old collections');

    // Create Demo Users
    const salt = await bcrypt.genSalt(10);
    const demoPassword = await bcrypt.hash('AgriTrade@2026', salt);
    const adminPassword = await bcrypt.hash('password@123', salt);

    const usersToCreate = [
      {
        name: 'Kasani Manikanta',
        email: 'kasanimanikanta2005@gmail.com',
        phone: '+91 99123 45678',
        password: adminPassword,
        role: 'admin',
        organization: 'AgriTrade Hub AI National Mission',
        location: { city: 'Hyderabad', state: 'Telangana' },
      },
      // 5 Farmers
      {
        name: 'Ramesh Reddy',
        email: 'farmer.ramesh@agritradehub.ai',
        phone: '+91 98481 22334',
        password: demoPassword,
        role: 'farmer',
        organization: 'Guntur Kisan Producers Cooperative',
        location: { city: 'Guntur', state: 'Andhra Pradesh' },
      },
      {
        name: 'Lakshmi Agro FPO',
        email: 'fpo.lakshmi@agritradehub.ai',
        phone: '+91 98482 33445',
        password: demoPassword,
        role: 'farmer',
        organization: 'Lakshmi Farmer Producer Company Ltd',
        location: { city: 'Warangal', state: 'Telangana' },
      },
      {
        name: 'Balasaheb Patil',
        email: 'farmer.balasaheb@agritradehub.ai',
        phone: '+91 98482 44556',
        password: demoPassword,
        role: 'farmer',
        organization: 'Nasik Onion Cultivators Group',
        location: { city: 'Nashik', state: 'Maharashtra' },
      },
      {
        name: 'Suresh Kumar Yadav',
        email: 'farmer.suresh@agritradehub.ai',
        phone: '+91 98482 55667',
        password: demoPassword,
        role: 'farmer',
        organization: 'Agra Potato Growers Sangh',
        location: { city: 'Agra', state: 'Uttar Pradesh' },
      },
      {
        name: 'Gurpreet Singh Dhillon',
        email: 'farmer.gurpreet@agritradehub.ai',
        phone: '+91 98482 66778',
        password: demoPassword,
        role: 'farmer',
        organization: 'Majha Basmati Farmers Union',
        location: { city: 'Amritsar', state: 'Punjab' },
      },
      // 5 Sellers
      {
        name: 'Suresh Kumar Trading',
        email: 'seller.suresh@agritradehub.ai',
        phone: '+91 98483 44556',
        password: demoPassword,
        role: 'seller',
        organization: 'AgriDirect Merchant Network',
        location: { city: 'Hyderabad', state: 'Telangana' },
      },
      {
        name: 'Ramesh Agro Mandi',
        email: 'seller.ramesh@agritradehub.ai',
        phone: '+91 98483 55667',
        password: demoPassword,
        role: 'seller',
        organization: 'Ramesh Agro Enterprises',
        location: { city: 'Guntur', state: 'Andhra Pradesh' },
      },
      {
        name: 'GreenField Commodity Traders',
        email: 'seller.greenfield@agritradehub.ai',
        phone: '+91 98483 66778',
        password: demoPassword,
        role: 'seller',
        organization: 'GreenField Agro Exporters Ltd',
        location: { city: 'Vijayawada', state: 'Andhra Pradesh' },
      },
      {
        name: 'Deccan Spice & Grain Merchants',
        email: 'seller.deccan@agritradehub.ai',
        phone: '+91 98483 77889',
        password: demoPassword,
        role: 'seller',
        organization: 'Deccan Mandi Trading Co',
        location: { city: 'Warangal', state: 'Telangana' },
      },
      {
        name: 'Kisan Mitra Agro Agencies',
        email: 'seller.kisanmitra@agritradehub.ai',
        phone: '+91 98483 88990',
        password: demoPassword,
        role: 'seller',
        organization: 'Kisan Mitra Retail Hub',
        location: { city: 'Nizamabad', state: 'Telangana' },
      },
      // 6 Consumers
      {
        name: 'Anita Sharma',
        email: 'consumer.anita@agritradehub.ai',
        phone: '+91 98484 55667',
        password: demoPassword,
        role: 'consumer',
        organization: 'Household Retail Consumer',
        location: { city: 'Bengaluru', state: 'Karnataka' },
      },
      {
        name: 'Pooja Verma',
        email: 'consumer.pooja@agritradehub.ai',
        phone: '+91 98484 66778',
        password: demoPassword,
        role: 'consumer',
        organization: 'Community Organic Buyer Group',
        location: { city: 'Hyderabad', state: 'Telangana' },
      },
      {
        name: 'Rajesh Nambiar',
        email: 'consumer.rajesh@agritradehub.ai',
        phone: '+91 98484 77889',
        password: demoPassword,
        role: 'consumer',
        organization: 'Kochi Retail Consumer',
        location: { city: 'Kochi', state: 'Kerala' },
      },
      {
        name: 'Sneha Patel',
        email: 'consumer.sneha@agritradehub.ai',
        phone: '+91 98484 88990',
        password: demoPassword,
        role: 'consumer',
        organization: 'Ahmedabad Food Collective',
        location: { city: 'Ahmedabad', state: 'Gujarat' },
      },
      {
        name: 'Vikram Joshi',
        email: 'consumer.vikram@agritradehub.ai',
        phone: '+91 98484 99001',
        password: demoPassword,
        role: 'consumer',
        organization: 'Pune Organic Consumer',
        location: { city: 'Pune', state: 'Maharashtra' },
      },
      {
        name: 'Kavitha Rao',
        email: 'consumer.kavitha@agritradehub.ai',
        phone: '+91 98484 11223',
        password: demoPassword,
        role: 'consumer',
        organization: 'Visakhapatnam Fresh Produce Buyer',
        location: { city: 'Visakhapatnam', state: 'Andhra Pradesh' },
      },
      // 4 Bulk Buyers
      {
        name: 'Reliance Retail Agritech',
        email: 'buyer.reliance@agritradehub.ai',
        phone: '+91 98485 66778',
        password: demoPassword,
        role: 'buyer',
        organization: 'Institutional Procurement Hub',
        location: { city: 'Hyderabad', state: 'Telangana' },
      },
      {
        name: 'ITC Agri Business Division',
        email: 'buyer.itc@agritradehub.ai',
        phone: '+91 98485 77889',
        password: demoPassword,
        role: 'buyer',
        organization: 'ITC Choupal Fresh Procurement',
        location: { city: 'Guntur', state: 'Andhra Pradesh' },
      },
      {
        name: 'BigBasket Fresh Logistics',
        email: 'buyer.bigbasket@agritradehub.ai',
        phone: '+91 98485 88990',
        password: demoPassword,
        role: 'buyer',
        organization: 'Innovative Retail Concepts Pvt Ltd',
        location: { city: 'Bengaluru', state: 'Karnataka' },
      },
      {
        name: 'Heritage Foods Procurement',
        email: 'buyer.heritage@agritradehub.ai',
        phone: '+91 98485 99001',
        password: demoPassword,
        role: 'buyer',
        organization: 'Heritage Foods Processing Division',
        location: { city: 'Hyderabad', state: 'Telangana' },
      },
    ];

    const createdUsers = await User.insertMany(usersToCreate);
    console.log(`[Seed] Created ${createdUsers.length} standard demo users with password 'AgriTrade@2026'`);

    const adminUser = createdUsers.find((u) => u.role === 'admin');
    const farmerUsers = createdUsers.filter((u) => u.role === 'farmer');
    const sellerUsers = createdUsers.filter((u) => u.role === 'seller');
    const consumerUsers = createdUsers.filter((u) => u.role === 'consumer');
    const buyerUsers = createdUsers.filter((u) => u.role === 'buyer');

    // Create 35 Products from masterProductCatalog with strict unique product media
    const productsToInsert = masterProductCatalog.map((p, idx) => {
      const assignedFarmer = farmerUsers[idx % farmerUsers.length];
      const assignedSeller = sellerUsers[idx % sellerUsers.length];

      return {
        ...p,
        farmer: assignedFarmer._id,
        farmerName: p.farmerName || assignedFarmer.organization || assignedFarmer.name,
        seller: assignedSeller._id,
        sellerName: p.sellerName || assignedSeller.organization || assignedSeller.name,
        images: p.images || [p.image],
        gallery: p.gallery || p.images || [p.image],
        video: p.video || null,
        specifications: p.specifications || {},
      };
    });

    const insertedProducts = await Product.insertMany(productsToInsert);
    console.log(`[Seed] Created ${insertedProducts.length} unique products with verified authentic media!`);

    // Create 5 Realistic Orders
    const ordersToInsert = [
      {
        orderId: 'AGRI-982143-2026',
        customer: consumerUsers[0]._id,
        customerName: consumerUsers[0].name,
        customerEmail: consumerUsers[0].email,
        customerPhone: consumerUsers[0].phone,
        shippingAddress: {
          street: 'Flat 402, Green Meadows, Gachibowli',
          city: 'Hyderabad',
          state: 'Telangana',
          pincode: '500032',
        },
        items: [
          {
            product: insertedProducts[0]._id,
            name: insertedProducts[0].name,
            price: insertedProducts[0].price,
            quantity: 25,
            unit: insertedProducts[0].unit,
            image: insertedProducts[0].image,
            subtotal: insertedProducts[0].price * 25,
            farmerId: insertedProducts[0].farmer,
          },
          {
            product: insertedProducts[1]._id,
            name: insertedProducts[1].name,
            price: insertedProducts[1].price,
            quantity: 30,
            unit: insertedProducts[1].unit,
            image: insertedProducts[1].image,
            subtotal: insertedProducts[1].price * 30,
            sellerId: insertedProducts[1].seller,
          },
        ],
        subtotal: insertedProducts[0].price * 25 + insertedProducts[1].price * 30,
        deliveryFee: 0,
        total: insertedProducts[0].price * 25 + insertedProducts[1].price * 30,
        paymentMethod: 'Razorpay Sandbox',
        paymentStatus: 'paid',
        paymentId: 'pay_test_sih2026_01',
        orderStatus: 'out_for_delivery',
        trackingHistory: [
          { status: 'confirmed', note: 'Order verified and accepted by Kisan Producer Group', timestamp: new Date(Date.now() - 36 * 3600 * 1000) },
          { status: 'packed', note: 'Crated in ventilated crates at Guntur Hub', timestamp: new Date(Date.now() - 18 * 3600 * 1000) },
          { status: 'dispatched', note: 'Dispatched via Eicher Reefer Express', timestamp: new Date(Date.now() - 6 * 3600 * 1000) },
          { status: 'out_for_delivery', note: 'Driver assigned: Srinivas (+91 94401 22334)', timestamp: new Date() },
        ],
        customerEmailSent: true,
        adminEmailSent: true,
      },
      {
        orderId: 'AGRI-773192-2026',
        customer: consumerUsers[1]._id,
        customerName: consumerUsers[1].name,
        customerEmail: consumerUsers[1].email,
        customerPhone: consumerUsers[1].phone,
        shippingAddress: {
          street: 'B-12, Madhapur IT Corridor',
          city: 'Hyderabad',
          state: 'Telangana',
          pincode: '500081',
        },
        items: [
          {
            product: insertedProducts[3]._id, // Banganapalli Mangoes
            name: insertedProducts[3].name,
            price: insertedProducts[3].price,
            quantity: 10,
            unit: insertedProducts[3].unit,
            image: insertedProducts[3].image,
            subtotal: insertedProducts[3].price * 10,
            sellerId: insertedProducts[3].seller,
          },
        ],
        subtotal: insertedProducts[3].price * 10,
        deliveryFee: 0,
        total: insertedProducts[3].price * 10,
        paymentMethod: 'UPI Test',
        paymentStatus: 'paid',
        paymentId: 'pay_test_sih2026_02',
        orderStatus: 'delivered',
        trackingHistory: [
          { status: 'confirmed', note: 'Direct Farm Gate Order Booked', timestamp: new Date(Date.now() - 48 * 3600 * 1000) },
          { status: 'delivered', note: 'Delivered in eco-friendly protective packaging', timestamp: new Date(Date.now() - 12 * 3600 * 1000) },
        ],
        customerEmailSent: true,
        adminEmailSent: true,
      },
      {
        orderId: 'AGRI-551940-2026',
        customer: consumerUsers[2]._id,
        customerName: consumerUsers[2].name,
        customerEmail: consumerUsers[2].email,
        customerPhone: consumerUsers[2].phone,
        shippingAddress: {
          street: 'Marine Drive Road 4',
          city: 'Kochi',
          state: 'Kerala',
          pincode: '682011',
        },
        items: [
          {
            product: insertedProducts[5]._id, // Basmati Rice
            name: insertedProducts[5].name,
            price: insertedProducts[5].price,
            quantity: 50,
            unit: insertedProducts[5].unit,
            image: insertedProducts[5].image,
            subtotal: insertedProducts[5].price * 50,
            sellerId: insertedProducts[5].seller,
          },
        ],
        subtotal: insertedProducts[5].price * 50,
        deliveryFee: 0,
        total: insertedProducts[5].price * 50,
        paymentMethod: 'Razorpay Sandbox',
        paymentStatus: 'paid',
        paymentId: 'pay_test_sih2026_03',
        orderStatus: 'dispatched',
        trackingHistory: [
          { status: 'confirmed', note: 'Stock verified at Punjab Agro depot', timestamp: new Date(Date.now() - 24 * 3600 * 1000) },
          { status: 'dispatched', note: 'In transit via South Central Express Rail Freight', timestamp: new Date(Date.now() - 4 * 3600 * 1000) },
        ],
        customerEmailSent: true,
        adminEmailSent: true,
      },
      {
        orderId: 'AGRI-338210-2026',
        customer: consumerUsers[3]._id,
        customerName: consumerUsers[3].name,
        customerEmail: consumerUsers[3].email,
        customerPhone: consumerUsers[3].phone,
        shippingAddress: {
          street: 'Satellite Area, Block C',
          city: 'Ahmedabad',
          state: 'Gujarat',
          pincode: '380015',
        },
        items: [
          {
            product: insertedProducts[7]._id, // Guntur Teja Chillies
            name: insertedProducts[7].name,
            price: insertedProducts[7].price,
            quantity: 20,
            unit: insertedProducts[7].unit,
            image: insertedProducts[7].image,
            subtotal: insertedProducts[7].price * 20,
            sellerId: insertedProducts[7].seller,
          },
        ],
        subtotal: insertedProducts[7].price * 20,
        deliveryFee: 0,
        total: insertedProducts[7].price * 20,
        paymentMethod: 'UPI Test',
        paymentStatus: 'paid',
        paymentId: 'pay_test_sih2026_04',
        orderStatus: 'confirmed',
        trackingHistory: [
          { status: 'confirmed', note: 'Order confirmed and registered in cold store', timestamp: new Date() },
        ],
        customerEmailSent: true,
        adminEmailSent: true,
      },
      {
        orderId: 'AGRI-129485-2026',
        customer: consumerUsers[4]._id,
        customerName: consumerUsers[4].name,
        customerEmail: consumerUsers[4].email,
        customerPhone: consumerUsers[4].phone,
        shippingAddress: {
          street: 'Kothrud Hill View, Plot 19',
          city: 'Pune',
          state: 'Maharashtra',
          pincode: '411038',
        },
        items: [
          {
            product: insertedProducts[9]._id, // Lakadong Turmeric
            name: insertedProducts[9].name,
            price: insertedProducts[9].price,
            quantity: 15,
            unit: insertedProducts[9].unit,
            image: insertedProducts[9].image,
            subtotal: insertedProducts[9].price * 15,
            farmerId: insertedProducts[9].farmer,
          },
        ],
        subtotal: insertedProducts[9].price * 15,
        deliveryFee: 0,
        total: insertedProducts[9].price * 15,
        paymentMethod: 'Razorpay Sandbox',
        paymentStatus: 'paid',
        paymentId: 'pay_test_sih2026_05',
        orderStatus: 'delivered',
        trackingHistory: [
          { status: 'confirmed', note: 'Dispatched from Meghalaya Hills FPO', timestamp: new Date(Date.now() - 72 * 3600 * 1000) },
          { status: 'delivered', note: 'Successfully delivered to customer', timestamp: new Date(Date.now() - 2 * 3600 * 1000) },
        ],
        customerEmailSent: true,
        adminEmailSent: true,
      },
    ];

    const createdOrders = await Order.insertMany(ordersToInsert);
    console.log(`[Seed] Created 5 diverse customer orders across multiple sellers & states!`);

    // Create Verified Reviews
    await Review.create({
      product: insertedProducts[0]._id,
      user: consumerUsers[0]._id,
      userName: consumerUsers[0].name,
      order: createdOrders[0]._id,
      rating: 5,
      comment: 'Super fresh tomatoes! Delivered directly from Guntur farmland. No damage and firm texture.',
      isVerifiedPurchase: true,
    });

    // Create 3 Bulk Requirements
    await BuyerRequirement.create([
      {
        buyer: buyerUsers[0]._id,
        buyerName: buyerUsers[0].name,
        buyerEmail: buyerUsers[0].email,
        buyerPhone: buyerUsers[0].phone,
        productName: 'Tomatoes',
        category: 'Vegetables',
        quantity: 5000,
        unit: 'kg',
        maxPricePerUnit: 35,
        targetLocation: 'Hyderabad Central Food Logistics Hub',
        targetDate: new Date(Date.now() + 5 * 24 * 3600 * 1000),
        status: 'open',
        matchedSuppliers: [
          {
            supplierId: farmerUsers[0]._id,
            supplierName: farmerUsers[0].organization || farmerUsers[0].name,
            supplierRole: 'Farmer / FPO',
            availableQuantity: 2500,
            offeredPrice: 32,
            location: 'Guntur, Andhra Pradesh',
            distanceKm: 240,
            matchScore: 94,
            matchReasons: [
              'Produce variety matches requirement',
              'Price ₹32/kg is ₹3 below your max ceiling of ₹35',
              'Batch availability: 2,500 kg ready for harvest',
              'Proximity match: Direct highway connection to Hyderabad',
            ],
            status: 'pending',
          },
        ],
      },
      {
        buyer: buyerUsers[1]._id,
        buyerName: buyerUsers[1].name,
        buyerEmail: buyerUsers[1].email,
        buyerPhone: buyerUsers[1].phone,
        productName: 'Aromatic Basmati Rice',
        category: 'Grains',
        quantity: 15000,
        unit: 'kg',
        maxPricePerUnit: 105,
        targetLocation: 'Guntur Export Processing Terminal',
        targetDate: new Date(Date.now() + 10 * 24 * 3600 * 1000),
        status: 'open',
        matchedSuppliers: [
          {
            supplierId: farmerUsers[4]._id,
            supplierName: farmerUsers[4].organization || farmerUsers[4].name,
            supplierRole: 'Farmer / FPO',
            availableQuantity: 5000,
            offeredPrice: 95,
            location: 'Amritsar, Punjab',
            distanceKm: 1850,
            matchScore: 91,
            matchReasons: [
              'Aromatic 1121 certified grain',
              'Export packaging certified',
            ],
            status: 'pending',
          },
        ],
      },
      {
        buyer: buyerUsers[2]._id,
        buyerName: buyerUsers[2].name,
        buyerEmail: buyerUsers[2].email,
        buyerPhone: buyerUsers[2].phone,
        productName: 'Nasik Red Onions',
        category: 'Vegetables',
        quantity: 8000,
        unit: 'kg',
        maxPricePerUnit: 32,
        targetLocation: 'Bengaluru Fresh Depot',
        targetDate: new Date(Date.now() + 7 * 24 * 3600 * 1000),
        status: 'open',
        matchedSuppliers: [
          {
            supplierId: farmerUsers[2]._id,
            supplierName: farmerUsers[2].organization || farmerUsers[2].name,
            supplierRole: 'Farmer / FPO',
            availableQuantity: 4500,
            offeredPrice: 28,
            location: 'Nashik, Maharashtra',
            distanceKm: 980,
            matchScore: 96,
            matchReasons: [
              'Sun-cured medium pungent variety',
              'Immediate transport dispatch ready',
            ],
            status: 'pending',
          },
        ],
      },
    ]);

    // Create Initial Email Audit Logs
    const EmailLog = (await import('../models/EmailLog.js')).default;
    await EmailLog.create([
      {
        type: 'order_confirmation_customer',
        recipient: 'consumer.anita@agritradehub.ai',
        subject: 'Order #AGRI-982143-2026 Confirmed – AgriTrade Hub AI',
        referenceId: 'AGRI-982143-2026',
        status: 'sent',
      },
      {
        type: 'order_notification_admin',
        recipient: 'kasanimanikanta2005@gmail.com',
        subject: 'High Priority Dispatch Notice: Order #AGRI-982143-2026',
        referenceId: 'AGRI-982143-2026',
        status: 'sent',
      },
      {
        type: 'order_confirmation_customer',
        recipient: 'consumer.pooja@agritradehub.ai',
        subject: 'Order #AGRI-773192-2026 Confirmed – AgriTrade Hub AI',
        referenceId: 'AGRI-773192-2026',
        status: 'sent',
      },
    ]);

    console.log('[Seed] Database successfully seeded with 22 products, 21 multi-role users, verified reviews, 5 orders & email logs!');
    if (process.argv[1] && process.argv[1].endsWith('seedData.js')) {
      process.exit(0);
    }
  } catch (error) {
    console.error('[Seed Error]:', error);
    if (process.argv[1] && process.argv[1].endsWith('seedData.js')) {
      process.exit(1);
    }
  }
};

// Run seed if executed directly
if (process.argv[1] && process.argv[1].endsWith('seedData.js')) {
  seedDatabase();
}
